version: "2"
linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - ireturn
    - lll
    - exhaustruct
    - gochecknoglobals
    - err113
    - godot
    - godox
    - prealloc
    - varnamelen
    - gosmopolitan
    - mnd

  exclusions:
    warn-unused: true
